### ISSUE TITLE
Setting PG to read-only

### ISSUE THREAD

**Issue by jgn** [tessro/oculus#9]
Something you might want to try:

I have found it useful on PG to set the transaction to readonly. Example:

```
connection.execute("set transaction read only; " + sql)
```

To be sure, a user could just unset it, but it's better than nothing. You could trigger it with a checkbox.

There may be something similar for MySQL.

**Comment by tessro** [comment]
Thanks for the tip.  I'd prefer to leave this type of thing up to database permissions.  There are valid reasons for not using a readonly user, it's just a tip for people who are using the tool in analytical environments who probably don't want their data updated or destroyed.

**Comment by jgn** [comment]
Sure. Just don't underestimate the end user's love of a protection layer that can be handled with a checkbox. :-)
